import type { Locale } from "@/lib/i18n/config";

/**
 * Locale-owned copy for the document chrome shared by every template.
 *
 * Keeping header identifier, approval, signature, stamp, verification, and
 * legal notice labels in one registry prevents individual templates from
 * assembling bilingual blocks or silently falling back to the other locale.
 */
const SHARED_DOCUMENT_SECTION_COPY = {
  en: {
    header: {
      taxRegistrationNumber: "Tax registration number",
      registrationNumber: "Registration / license number",
    },
    verification: {
      genericTitle: "Verification",
      recordTitle: "Record verification",
      clinicalTitle: "Order verification",
      genericCaption: "Scan to verify this issued record on ClinicFlow.",
      clinicalCaption: "Scan to verify this issued clinical document.",
      financialCaption:
        "Scan to verify this medical financial record on the ClinicFlow audit trail.",
    },
    signatures: {
      authorized: "Authorized signature",
      recipient: "Recipient signature",
      patient: "Patient signature",
      physician: "Responsible physician signature",
      manual: "Blank area for manual signature",
      medicalDirector: "Medical director",
      employee: "Employee signature",
      accountsAuthorized: "Accounts / authorized signature",
      accountingApproval: "Accounting approval / Authorized signature",
      clinicAdministrator: "Clinic administrator",
    },
    stamps: {
      clinic: "Clinic stamp",
      physician: "Physician stamp / seal",
      clinicApproval: "Clinic approval / official stamp",
    },
    notices: {
      prescriptionValidity:
        "This prescription is not considered valid unless signed, stamped, or both by the responsible physician.",
      controlledPrescription:
        "Clinic-issued prescription. Not valid for controlled substances unless an approved compliance profile is active.",
    },
    footer: {
      medicalRecordsSystem: "ClinicFlow Medical Records System",
      documentSystem: "ClinicFlow Document System",
      allRights: "© 2026 ClinicFlow. All rights reserved.",
      authenticity: "Authenticity is confirmed only by the verification record.",
      confidentialFinancial: "Confidential medical financial record.",
      generatedBy: "Generated by ClinicFlow.",
    },
  },
  ar: {
    header: {
      taxRegistrationNumber: "الرقم الضريبي",
      registrationNumber: "رقم الترخيص / التسجيل",
    },
    verification: {
      genericTitle: "التحقق",
      recordTitle: "التحقق من السجل",
      clinicalTitle: "التحقق من المستند",
      genericCaption: "امسح الرمز للتحقق من السجل الصادر عبر كلينيك فلو.",
      clinicalCaption: "امسح الرمز للتحقق من المستند السريري الصادر.",
      financialCaption:
        "امسح الرمز للتحقق من هذا السجل المالي الطبي عبر سجل تدقيق كلينيك فلو.",
    },
    signatures: {
      authorized: "التوقيع المعتمد",
      recipient: "توقيع المستلم",
      patient: "توقيع المريض",
      physician: "توقيع الطبيب المسؤول",
      manual: "مساحة فارغة للتوقيع اليدوي",
      medicalDirector: "المدير الطبي",
      employee: "توقيع الموظف",
      accountsAuthorized: "الحسابات / التوقيع المعتمد",
      accountingApproval: "اعتماد المحاسبة / التوقيع المعتمد",
      clinicAdministrator: "مدير العيادة",
    },
    stamps: {
      clinic: "ختم العيادة",
      physician: "ختم الطبيب",
      clinicApproval: "اعتماد العيادة / الختم الرسمي",
    },
    notices: {
      prescriptionValidity:
        "لا تُعد هذه الوصفة الطبية معتمدة إلا بعد توقيع الطبيب أو ختمه أو كليهما.",
      controlledPrescription:
        "وصفة صادرة عن العيادة ولا تصلح للأدوية الخاضعة للرقابة دون ملف امتثال معتمد.",
    },
    footer: {
      medicalRecordsSystem: "نظام كلينيك فلو للسجلات الطبية",
      documentSystem: "نظام مستندات كلينيك فلو",
      allRights: "© 2026 كلينيك فلو. جميع الحقوق محفوظة.",
      authenticity: "لا تُؤكد الأصالة إلا من خلال سجل التحقق.",
      confidentialFinancial: "سجل مالي طبي سري.",
      generatedBy: "صادر عن كلينيك فلو.",
    },
  },
} as const;

export type SharedDocumentSectionCopy =
  (typeof SHARED_DOCUMENT_SECTION_COPY)[keyof typeof SHARED_DOCUMENT_SECTION_COPY];

export function getSharedDocumentSectionCopy(
  locale: Locale,
): SharedDocumentSectionCopy {
  return SHARED_DOCUMENT_SECTION_COPY[locale];
}
