import Link from "next/link";
import { ArrowUpRight, Building2, CircleDollarSign, Clock3, CreditCard, MailPlus, TrendingUp, Users } from "lucide-react";
import { ExecutiveCharts } from "@/components/operator/executive-charts";
import { OrphanTruncationWarning } from "@/components/operator/orphan-truncation-warning";
import { getOperatorAnalytics } from "@/lib/operator-analytics";
import { listOperatorClinics, listOrphanedSignupUsers } from "@/lib/supabase/admin";
import { createClient } from "@/lib/supabase/server";

function Stat({label,value,trend,icon:Icon}:{label:string;value:string|number;trend?:number;icon:typeof Building2}) {
  return <article className="rounded-2xl border bg-card p-5 shadow-sm"><div className="flex justify-between"><div><p className="text-sm text-muted-foreground">{label}</p><p className="mt-2 text-3xl font-bold tabular-nums">{value}</p></div><Icon className="size-5 text-primary"/></div>{trend!==undefined?<p className="mt-3 text-xs text-emerald-600">{trend.toFixed(1)}% this month</p>:null}</article>;
}

async function Operations() {
  const db=await createClient(),now=new Date(),soon=new Date(now.getTime()+7*86400000).toISOString(),month=`${now.getUTCFullYear()}-${String(now.getUTCMonth()+1).padStart(2,"0")}-01`;
  const[status,expiring,usage,pending,open,coupons,overrides,clinics,orphans]=await Promise.all([db.rpc("get_public_registration_status"),db.from("subscriptions").select("clinic_id, trial_ends_at").eq("status","trialing").gt("trial_ends_at",now.toISOString()).lte("trial_ends_at",soon),db.from("usage_counters").select("clinic_id, metric, used, limit_snapshot").eq("period_start",month).order("used",{ascending:false}).limit(10),db.from("clinic_invitations").select("id",{count:"exact",head:true}).eq("status","pending").is("token_hash",null),db.from("clinic_invitations").select("id",{count:"exact",head:true}).eq("status","pending").not("token_hash","is",null),db.from("coupons").select("id",{count:"exact",head:true}).eq("is_active",true),db.from("clinic_feature_overrides").select("clinic_id",{count:"exact",head:true}),listOperatorClinics(),listOrphanedSignupUsers()]);
  const names=new Map((clinics.data??[]).map(c=>[c.id,c.name])),reg=status.data?.[0];
  return <section className="space-y-4"><div><h2 className="text-xl font-semibold">Operations</h2><p className="text-sm text-muted-foreground">Registration mode: <span className="font-medium text-foreground">{reg?.registration_mode??"unknown"}</span></p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Accepted this week" value={`${reg?.accepted_clinics_this_week??0} / ${reg?.weekly_invite_limit??"—"}`} icon={Users}/><Stat label="Pending requests" value={pending.count??0} icon={MailPlus}/><Stat label="Open invitations" value={open.count??0} icon={MailPlus}/><Stat label="Coupons / overrides" value={`${coupons.count??0} / ${overrides.count??0}`} icon={CreditCard}/></div><div className="grid gap-4 lg:grid-cols-3"><div className="rounded-2xl border bg-card p-5"><h3 className="font-semibold">Trials expiring in 7 days</h3>{(expiring.data??[]).map(r=><p className="mt-2 text-sm" key={r.clinic_id}>{names.get(r.clinic_id)??r.clinic_id} · {r.trial_ends_at?.slice(0,10)}</p>)}</div><div className="rounded-2xl border bg-card p-5"><h3 className="font-semibold">Top usage this month</h3>{(usage.data??[]).map(r=><p className="mt-2 text-sm" key={`${r.clinic_id}-${r.metric}`}>{names.get(r.clinic_id)??r.clinic_id} · {r.metric}: {r.used}/{r.limit_snapshot}</p>)}</div><div className="rounded-2xl border bg-card p-5"><h3 className="font-semibold">Orphaned signup accounts</h3><OrphanTruncationWarning truncated={orphans.data?.truncated??false}/>{orphans.error?<p className="text-destructive">Lookup failed.</p>:(orphans.data?.orphans??[]).map(o=><p className="mt-2 text-sm" key={o.id}>{o.email??o.id}</p>)}{orphans.data?.orphans.length===0?<p className="mt-2 text-sm text-muted-foreground">None.</p>:null}</div></div><div className="grid gap-4 lg:grid-cols-2"><div className="rounded-2xl border border-dashed p-5"><h3 className="font-semibold">Delivery health</h3><p className="text-sm text-muted-foreground">Available with P3 messaging.</p></div><div className="rounded-2xl border border-dashed p-5"><h3 className="font-semibold">Error summaries</h3><p className="text-sm text-muted-foreground">Review the Sentry project dashboard.</p></div></div></section>;
}

export default async function MissionControlPage(){const d=await getOperatorAnalytics();return <><header className="flex flex-wrap items-end justify-between gap-4"><div><p className="text-sm font-medium text-primary">Executive overview</p><h1 className="text-3xl font-bold">Mission Control</h1><p className="text-muted-foreground">Platform health and growth, without tenant clinical data.</p></div><Link href="/operator/reports" className="inline-flex items-center gap-2 rounded-xl border px-4 py-2">Open reports <ArrowUpRight className="size-4"/></Link></header><section className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4"><Stat label="Active clinics" value={d.activeClinics} icon={Building2}/><Stat label="Trial clinics" value={d.trialClinics} icon={Clock3}/><Stat label="Paid clinics" value={d.paidClinics} icon={CreditCard}/><Stat label="Revenue overview" value={`$${d.revenueUsd.toLocaleString()}`} icon={CircleDollarSign}/><Stat label="Monthly growth" value={`${d.monthlyGrowth.toFixed(1)}%`} trend={d.monthlyGrowth} icon={TrendingUp}/><Stat label="User growth" value={`${d.userGrowth.toFixed(1)}%`} trend={d.userGrowth} icon={Users}/><Stat label="Clinic growth" value={`${d.clinicGrowth.toFixed(1)}%`} trend={d.clinicGrowth} icon={Building2}/></section><ExecutiveCharts mix={d.subscriptionMix} growth={d.clinicSeries}/><section className="grid gap-6 lg:grid-cols-2"><div className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Recent activity</h2>{d.recentActivity.map(a=><p key={a.id} className="mt-2 text-sm">{a.action} · {a.targetType}</p>)}</div><div className="rounded-2xl border bg-card p-5"><h2 className="font-semibold">Quick actions</h2><Link className="mt-3 block" href="/operator/invitations"><MailPlus className="me-2 inline size-4"/>Create invitation</Link><Link className="mt-3 block" href="/operator/clinics"><Building2 className="me-2 inline size-4"/>Manage clinics</Link></div></section><Operations/></>}
