export const marketingCopy = {
  brand: "ClinicFlow",
  nav: {
    label: "Main navigation",
    menu: "Open navigation menu",
    menuTitle: "Navigate ClinicFlow",
    product: "Product",
    features: "Features",
    pricing: "Pricing",
    faq: "FAQ",
    contact: "Contact",
    login: "Log in",
  },
  hero: {
    eyebrow: "Clinic operations, beautifully organized",
    title: "Your clinic, in one calm workspace.",
    body: "ClinicFlow brings appointments, patient records, billing, and daily operations together—so your team can focus on care.",
    primary: "Try ClinicFlow",
    secondary: "Request early access",
    assurances: ["Role-based access", "No card required", "Guided onboarding"],
    preview: {
      date: "Monday, July 12",
      greeting: "Good morning, Dr. Noor",
      metrics: [["12", "Appointments"], ["4", "Waiting"], ["82%", "Capacity"]],
      flowTitle: "Today’s flow",
      appointments: ["09:00  Consultation", "10:15  Follow-up", "11:30  New patient"],
      patientsValue: "248",
      patientsLabel: "patients cared for this month",
    },
  },
  product: {
    eyebrow: "One connected workspace",
    title: "Less operational noise. More room for care.",
    body: "ClinicFlow replaces scattered calendars, files, and spreadsheets with a coherent daily system. Every role sees what they need, every action stays traceable, and the clinic keeps moving.",
  },
  features: {
    eyebrow: "Everything in its place",
    title: "Designed around a real clinic day.",
    items: [
      { title: "Appointments that stay on track", body: "Flexible calendars, clear statuses, and a complete view of every clinic day." },
      { title: "Patient context, close at hand", body: "Records, notes, documents, packages, and follow-ups in one dependable timeline." },
      { title: "A clearer view of performance", body: "Understand revenue, workload, cancellations, and team activity without spreadsheet archaeology." },
    ],
  },
  trust: {
    eyebrow: "Built for trust",
    title: "The right access for every role.",
    body: "ClinicFlow’s multi-tenant architecture, row-level data isolation, and role-based permissions keep clinic information within the right boundaries.",
    assurance: "Secure by design, from database to interface.",
    roles: [
      { name: "Administrator", access: "Full clinic access" },
      { name: "Reception team", access: "Role-based access" },
      { name: "Clinic manager", access: "Role-based access" },
      { name: "Doctor", access: "Role-based access" },
    ],
  },
  pricing: {
    eyebrow: "Simple plans are taking shape",
    title: "Pricing that grows with your clinic.",
    body: "We’re finalizing plans with our early clinics. Join the cohort for guided onboarding and a direct voice in what comes next.",
    cta: "Join early access",
  },
  earlyAccess: {
    eyebrow: "Early access",
    title: "Build a calmer clinic with us.",
    body: "We welcome a small cohort each week and help every clinic get set up thoughtfully.",
    progress: (accepted: number, limit: number) => `${accepted} of ${limit} spots taken this week`,
    button: "Request an invitation",
    openButton: "Create your clinic",
    dialogTitle: "Request early access",
    dialogDescription: "Tell us about your clinic. We’ll be in touch after a thoughtful review.",
  },
  faq: {
    eyebrow: "Questions, answered",
    title: "A clear start.",
    expand: "+",
    items: [
      { question: "Who is ClinicFlow for?", answer: "Independent and multi-doctor private clinics that want one secure system for daily operations." },
      { question: "Can my whole team use it?", answer: "Yes. Admins, receptionists, managers, and doctors receive role-appropriate access and views." },
      { question: "How does early access work?", answer: "Request an invitation and our team will review your clinic. We onboard a limited number each week." },
      { question: "Is pricing available?", answer: "Plans are being finalized with our early clinics. We will publish clear pricing before general availability." },
    ],
  },
  footer: {
    tagline: "A calmer operating system for private clinics.",
    email: "hello@clinicflow.app",
    login: "Team login",
  },
} as const;
