/**
 * P11 — the presentation contract: what the model is allowed to *say* about
 * entities the database owns.
 *
 * ## The gap this closes
 *
 * Every layer below this one was already correct. `loadDoctorDirectory` is
 * clinic-scoped, `availableDoctorsInDepartment` filters to one department's
 * active, undeleted, not-currently-on-leave doctors, and
 * `assertRosterAuthority` now throws rather than trusting itself. And none of
 * that constrains the sentence the patient actually receives, because the reply
 * is free text generated by a language model that has *also* read a system
 * prompt, sixteen messages of history, and its own pre-training — all of which
 * contain plausible doctor names.
 *
 * So the device test that started this phase is exactly what the architecture
 * permitted: the server returned one Dermatology doctor and the patient was
 * shown two. Nothing had to be wrong in the query for that to happen, which is
 * why removing names from the prompt in P10 did not prevent it. A prompt rule
 * ("never name a doctor that is not in the list") is a request. This module is
 * the check.
 *
 * ## How it works
 *
 * 1. **A ledger.** Every patient tool result this turn is walked for the
 *    entities the server actually returned — doctors, departments, services —
 *    through named keys, never by guessing at shapes. That set is the only
 *    thing the reply may name.
 *
 * 2. **Two detectors, both grounded in real data.**
 *    * Any *clinic staff name* — from the live directory, including doctors of
 *      other departments and deactivated ones — that appears in the reply but
 *      not in the ledger. This is exact: it can only fire on a real person the
 *      server did not offer, and it catches a bare "1. Fatima Khalil" with no
 *      title at all.
 *    * Any name written after a doctor title ("Dr", "د.", "الدكتورة", …) that
 *      matches nothing in the ledger. This is what catches a name the model
 *      invented outright, which by definition is in no table anywhere.
 *
 * 3. **Repair, not refusal.** A violation is answered by regenerating the turn
 *    once with a corrective instruction naming the permitted set. If the second
 *    attempt is still ungrounded, the patient gets a deterministic sentence
 *    composed from the authoritative roster itself. The assistant stays
 *    conversational; entity *membership* stops being negotiable.
 *
 * Nothing here is an authorization boundary and nothing here reads identity.
 * It is a truthfulness check on one string, and it holds no state beyond the
 * turn it belongs to.
 */

import {
  literalScore,
  normalizeEntityText,
  type NamedEntity,
} from "@/lib/ai/entity-resolution";
import {
  formatPersonName,
  formatPersonNames,
  localizeEntityLabel,
  localizeEntityLabels,
} from "@/lib/ai/entity-labels";
import {
  formatPatientDate,
  formatPatientTime,
} from "@/lib/ai/patient-fact-reply";

// ---------------------------------------------------------------------------
// The ledger
// ---------------------------------------------------------------------------

export type EntityKind = "doctor" | "department" | "service" | "insurer";

export type GroundingLedger = {
  /** Walks one tool result and records the entities the server returned. */
  record(toolName: string, result: unknown): void;
  /** The names the reply may use, by kind. Normalized on read. */
  names(kind: EntityKind): readonly string[];
  /** Doctor ids the server offered this turn, for the roster invariant. */
  doctorIds(): readonly string[];
  /**
   * F-1 — every price the server itself returned this turn.
   *
   * The closed world for money. `enforcePatientFactReply` already renders a
   * price list deterministically once `list_department_services` has run, but a
   * turn where the model answers a price question *without* calling the tool
   * had no gate at all and the number went straight to the patient. A price is
   * the single worst thing for a clinic assistant to invent: it is quoted,
   * screenshotted and treated as a commitment, and unlike a doctor's name the
   * patient has no way to notice it is wrong.
   */
  prices(): readonly number[];
  /** True when a services/pricing tool returned this turn. */
  sawServices(): boolean;
  /** True when the insurance tool returned this turn. */
  sawInsurers(): boolean;
  /** True when at least one tool returned a doctor this turn. */
  sawDoctors(): boolean;
  /**
   * P11G — the tools that actually reached `execute` and returned this turn,
   * in call order, with repeats collapsed.
   *
   * The ledger is already the one place every patient tool result passes
   * through (`protectPatientTool` records here before sanitizing), so it is the
   * only place that can answer "did the required operation actually run?"
   * without a second interception point that could drift from this one. Names
   * only — a closed set of fifteen — never arguments and never results.
   */
  toolsSeen(): readonly string[];
  /**
   * The last raw result returned by a named tool on this turn.
   *
   * P11H — write truthfulness needs the server receipt, not merely evidence
   * that a tool happened to run. The value stays in this in-memory turn ledger
   * and is never written to audit logs. Callers must still validate its closed
   * shape before treating it as a committed entity.
   */
  resultFor(toolName: string): unknown | null;
};

/**
 * The keys whose values are doctors.
 *
 * A named list rather than a shape sniff: a walker that treated every
 * `{id, name}` it found as a doctor would silently promote departments,
 * services and insurers into the permitted doctor set, and the whole point of
 * this module is that the permitted set is small and deliberate.
 */
const DOCTOR_KEYS = new Set([
  "doctors",
  "other_doctors",
  "treating_doctor",
  "requested_doctor",
  "doctor",
]);
const DEPARTMENT_KEYS = new Set(["departments", "department"]);
const SERVICE_KEYS = new Set(["services", "service"]);
/** F-1 — the keys whose values are insurers, named for the same reason. */
const INSURER_KEYS = new Set(["providers", "provider"]);
/** F-1 — the tools whose receipts make a commercial claim answerable at all. */
const SERVICE_TOOLS = new Set(["list_department_services"]);
const INSURER_TOOLS = new Set(["list_clinic_insurance"]);
/** `candidates` means whatever `field` says it means. */
const FIELD_KEY = "field";

export function createGroundingLedger(): GroundingLedger {
  const doctors = new Map<string, string>();
  const departments = new Map<string, string>();
  const services = new Map<string, string>();
  const insurers = new Map<string, string>();
  const doctorIds = new Set<string>();
  const prices = new Set<number>();
  const toolsSeen = new Set<string>();
  const results = new Map<string, unknown>();
  let sawDoctors = false;

  function add(kind: EntityKind, value: unknown): void {
    if (Array.isArray(value)) {
      for (const item of value) add(kind, item);
      return;
    }
    if (typeof value === "string") {
      remember(kind, value);
      return;
    }
    if (!value || typeof value !== "object") return;
    const row = value as Record<string, unknown>;
    if (typeof row.name === "string") remember(kind, row.name);
    // Appointment rows name their doctor rather than nesting one.
    if (typeof row.doctor_name === "string") remember("doctor", row.doctor_name);
    if (kind === "doctor" && typeof row.id === "string") doctorIds.add(row.id);
    // A service row carries its own price. Recording it here — rather than
    // sweeping the whole result for numbers — is what keeps the allowed set to
    // prices the clinic actually configured.
    if (kind === "service") rememberPrice(row.price);
    if (Array.isArray(row.services)) add("service", row.services);
  }

  function rememberPrice(value: unknown): void {
    const price =
      typeof value === "number"
        ? value
        : typeof value === "string" && value.trim()
          ? Number(value.trim())
          : Number.NaN;
    if (Number.isFinite(price)) prices.add(price);
  }

  function remember(kind: EntityKind, name: string): void {
    const trimmed = name.trim();
    if (!trimmed) return;
    const key = normalizeEntityText(trimmed);
    if (!key) return;
    if (kind === "doctor") {
      doctors.set(key, trimmed);
      sawDoctors = true;
      return;
    }
    if (kind === "department") departments.set(key, trimmed);
    else if (kind === "insurer") insurers.set(key, trimmed);
    else services.set(key, trimmed);
  }

  function walk(node: unknown, depth: number): void {
    if (depth > 6 || !node || typeof node !== "object") return;
    if (Array.isArray(node)) {
      for (const item of node) walk(item, depth + 1);
      return;
    }
    const row = node as Record<string, unknown>;
    const field = typeof row[FIELD_KEY] === "string" ? (row[FIELD_KEY] as string) : null;
    for (const [key, value] of Object.entries(row)) {
      if (DOCTOR_KEYS.has(key)) add("doctor", value);
      else if (DEPARTMENT_KEYS.has(key)) add("department", value);
      else if (SERVICE_KEYS.has(key)) add("service", value);
      else if (INSURER_KEYS.has(key)) add("insurer", value);
      else if (key === "candidates" && field === "insurer") add("insurer", value);
      else if (key === "candidates" && field === "doctor") add("doctor", value);
      else if (key === "candidates" && field === "department") add("department", value);
      else if (key === "appointments") add("doctor", value);
      else walk(value, depth + 1);
    }
  }

  return {
    record(toolName, result) {
      if (typeof toolName === "string" && toolName) {
        toolsSeen.add(toolName);
        results.set(toolName, result);
      }
      walk(result, 0);
    },
    names(kind) {
      const map =
        kind === "doctor"
          ? doctors
          : kind === "department"
            ? departments
            : kind === "insurer"
              ? insurers
              : services;
      return [...map.values()];
    },
    doctorIds: () => [...doctorIds],
    prices: () => [...prices],
    sawDoctors: () => sawDoctors,
    sawServices: () => [...toolsSeen].some((tool) => SERVICE_TOOLS.has(tool)),
    sawInsurers: () => [...toolsSeen].some((tool) => INSURER_TOOLS.has(tool)),
    toolsSeen: () => [...toolsSeen],
    resultFor: (toolName) => results.get(toolName) ?? null,
  };
}

// ---------------------------------------------------------------------------
// Detection
// ---------------------------------------------------------------------------

/**
 * P11B — what changed here, and why the previous version let a phantom through.
 *
 * The reproduced defect was a numbered, bold-emphasised list of two invented
 * people, each written as `Dr. <First> <Last>` — the ordinary shape of an
 * English doctor list inside an Arabic reply. The old detector scored it
 * *grounded*. Two independent reasons, both mechanical:
 *
 *   1. **The title regex ate its own separator.** `\bdrs?\.?\b` cannot match
 *      `Dr.` followed by a space — there is no word boundary between `.` and
 *      ` ` — so it backtracked to the bare `Dr`, leaving the `.` as the first
 *      character of the remaining text. The span reader then split on sentence
 *      punctuation, found the `.` immediately, and produced an empty span. The
 *      single most common English shape for a doctor's name was therefore
 *      invisible to the check that exists to catch invented doctors' names.
 *      Every title below now consumes its own trailing punctuation *and* the
 *      whitespace after it, so the span always begins at the name.
 *
 *   2. **Markdown was scanned as content.** Bold emphasis carries asterisks
 *      into the token stream, and a list marker (`1.`, `-`, `•`) is punctuation
 *      the name reader had to step over. The text is now stripped of emphasis
 *      and list markers before anything looks at it.
 *
 * Fixing those two makes the reported reply fail the check. It does not make
 * the *class* impossible, which is what P11's own §11 admitted, so the check is
 * no longer only a search for bad names. On a turn whose subject is the roster,
 * it is a **closed-world membership test**: the set of people the reply may
 * name is the set the server returned, and anything name-shaped outside it is a
 * violation — whether or not it is a real person, whether or not it carries a
 * title. See `checkDoctorGrounding` for the three rules and their scopes.
 */

/**
 * Titles that introduce a doctor's name, in both languages the assistant
 * writes.
 *
 * Each alternative consumes the title, any abbreviating punctuation, and the
 * separator that follows, so `match[0].length` always lands on the first
 * character of what the writer intended as the name. The Arabic forms carry
 * explicit Unicode boundaries because `\b` is defined against `[A-Za-z0-9_]`
 * and therefore never exists between two Arabic letters.
 */
const DOCTOR_TITLE =
  /(?<![\p{L}\p{N}])(?:(?:drs?|doctors?|prof)|(?:ال)?(?:دكاترة|دكتوره|دكتورة|دكتور|د))(?:[.:\-–]+\s*|\s+)/giu;

/**
 * Markdown and list furniture, removed before any name is read.
 *
 * The model writes to WhatsApp, where `**bold**` is what the AI SDK produces and
 * the transport renders. Scanning the raw string meant a name was tokenized with
 * asterisks glued to it and matched nothing.
 */
export function stripPresentationMarkup(text: string): string {
  return text
    .replace(/[\u200B-\u200F\u202A-\u202E\u2066-\u2069\uFEFF]/gu, "")
    .replace(/[*_~`]+/gu, "")
    .replace(/^[ \t]*(?:\d{1,2}[.)]|[-–—•·])[ \t]+/gmu, "");
}

/**
 * Ordinary words. A span containing one is prose, not a person.
 *
 * The rule this drives is deliberately the *conservative* one for the
 * always-on detectors: a titled span is treated as a name only while its tokens
 * remain name-like. "الدكتور المعالج بتاعك هو د. Rana Wasfy" and "The doctor
 * currently available in Gamma Unit is Rana Wasfy" are both true sentences, and
 * a detector that read "currently available in Gamma" as a person would replace
 * them with a canned reply — a real regression traded for a hypothetical catch.
 *
 * On a roster-bearing turn the trade is different and the closed-world rule
 * applies instead, because there the canned reply is not a regression: it is the
 * correct answer to the question that was asked.
 */
const FUNCTION_WORDS = new Set([
  // English
  "a", "an", "the", "is", "are", "was", "were", "and", "or", "but", "in", "on",
  "at", "to", "of", "for", "with", "from", "by", "your", "our", "my", "their",
  "this", "that", "these", "those", "who", "will", "can", "you", "we", "they",
  "available", "treating", "current", "currently", "assigned", "only", "other",
  "another", "same", "new", "chosen", "selected", "right", "now", "today",
  "tomorrow", "here", "there", "please", "would", "like", "book", "booking",
  "appointment", "appointments", "department", "clinic", "doctors", "doctor",
  "sorry", "unfortunately", "there", "no", "not", "none", "any", "all", "which",
  // Arabic
  "هو", "هي", "هم", "في", "من", "الى", "إلى", "على", "عن", "مع", "و", "او", "أو",
  "ال", "التي", "الذي", "اللي", "ده", "دي", "دا", "كمان", "بس", "يعني", "عشان",
  "المعالج", "المتاح", "المتاحة", "المتاحين", "المناوب", "الحالي", "الوحيد",
  "بتاعك", "بتاعي", "المختار", "الخاص", "دلوقتي", "حاليا", "حالياً", "النهاردة",
  "بكرة", "بكرا", "تاني", "تانى", "التاني", "الثاني", "غيره", "الجديد", "نفس",
  "عندنا", "عندك", "قسم", "القسم", "موعد", "الموعد", "حجز", "الحجز", "د",
  "المسؤول", "المسئول", "اللى", "عندهم", "الدكاترة", "دكاترة", "اطباء", "أطباء",
  "معلش", "للأسف", "للاسف", "مفيش", "مش", "تحب", "ممكن", "طيب", "تمام", "أهلا",
  "اهلا", "العيادة", "الفريق", "الطبي", "عندي", "لينا", "ليك",
  // The bare (article-less) forms of the same describing words. "مفيش دكتور
  // متاح" opens a titled span with "متاح", and reading that as somebody's name
  // turned an honest "there is nobody free" into a grounding violation.
  "متاح", "متاحه", "متاحة", "متاحين", "موجود", "موجوده", "موجودة", "مناوب",
  "معالج", "واحد", "واحده", "واحدة", "حد", "اي", "أي", "انهي", "أنهي", "كده",
  "لسه", "بعد", "قبل", "معين", "محدد", "مخصص", "شاغر", "فاضي",
]);

const MAX_NAME_TOKENS = 4;

export type GroundingViolation = {
  /** The mention as it appeared, for the corrective instruction. */
  mention: string;
  source:
    /** A real person on the clinic's own staff who was not offered this turn. */
    | "clinic_directory"
    /** A name written after a doctor title that matches nothing offered. */
    | "titled_mention"
    /**
     * A roster-bearing turn named somebody with no authoritative roster behind
     * it at all. The strongest of the three: it does not need to parse a name.
     */
    | "unbacked_roster"
    /** A roster-bearing turn named somebody outside the server's roster. */
    | "unlisted_name";
};

export type GroundingCheck = {
  grounded: boolean;
  violations: readonly GroundingViolation[];
};

/**
 * Does this reply name a doctor the server did not return this turn?
 *
 * Three rules, with deliberately different scopes.
 *
 * **(1) Real staff, always.** Any name in the clinic's live directory —
 * including doctors of other departments and deactivated ones — that appears in
 * the reply but not in the ledger. Exact, title-independent, and it catches a
 * bare "1. Fatima Khalil". `clinicDoctors` deliberately spans the whole clinic:
 * those are precisely the names that are both real and not offerable, and a
 * check that only knew the offered set could not tell them from ordinary prose.
 *
 * **(2) Titled mentions, always.** A name written after a doctor title that
 * matches nothing offered. This is what catches a name that exists in no table
 * anywhere, and it is the rule the `Dr.` bug disabled.
 *
 * **(3) Closed world, on roster-bearing turns only.** When
 * `rosterBearing` is set — the patient asked who the doctors are, or a roster
 * tool ran, or the reply itself is written as a doctor list — membership stops
 * being a search for bad names and becomes a whitelist:
 *
 *   * with **no** server-returned roster (`allowedNames` empty), *any* doctor
 *     title or name-shaped list item at all is a violation. This rule needs to
 *     parse nothing, so no regex subtlety can defeat it: a reply that lists
 *     doctors when the server produced no doctors is wrong by construction.
 *   * with a server-returned roster, every name-shaped candidate — titled,
 *     enumerated, or a capitalized multi-word run mid-sentence — must be in it.
 *
 * That is the answer to P11 §11: an invented name no longer has to be
 * recognised *as* invented. On the turns where doctor membership matters it has
 * to be recognised as *offered*, and it cannot be.
 */
export function checkDoctorGrounding(input: {
  text: string;
  allowedNames: readonly string[];
  clinicDoctors: readonly NamedEntity[];
  /**
   * Non-doctor entities the server returned this turn — departments, services.
   *
   * They are legitimate to name and frequently look exactly like a person to a
   * name-shape heuristic ("Gamma Unit", "Physical Therapy"). Exempting them
   * from the closed-world sweep costs nothing, because the doctor rules above
   * are keyed on the doctor ledger and never consult this list.
   */
  allowedOtherNames?: readonly string[];
  /**
   * Is doctor membership the subject of this turn? Decided server-side by
   * `lib/ai/roster-intent.ts`; defaults to false so every existing caller keeps
   * exactly the pre-P11B behaviour of rules (1) and (2).
   */
  rosterBearing?: boolean;
}): GroundingCheck {
  const raw = input.text ?? "";
  if (!raw.trim()) return { grounded: true, violations: [] };
  const text = stripPresentationMarkup(raw);
  const allowed = input.allowedNames.map(normalizeEntityText).filter(Boolean);
  const otherEntities = (input.allowedOtherNames ?? [])
    .map(normalizeEntityText)
    .filter(Boolean);
  const violations: GroundingViolation[] = [];
  const seen = new Set<string>();

  const isAllowed = (candidate: string): boolean => {
    const key = normalizeEntityText(candidate);
    if (!key) return true;
    return allowed.some(
      (name) => name === key || literalScore(key, name) >= 0.78,
    );
  };
  const isOtherEntity = (candidate: string): boolean => {
    const key = normalizeEntityText(candidate);
    if (!key) return false;
    return otherEntities.some(
      (name) => name === key || literalScore(key, name) >= 0.86,
    );
  };
  const flag = (mention: string, source: GroundingViolation["source"]): void => {
    const key = normalizeEntityText(mention);
    if (!key || seen.has(key)) return;
    seen.add(key);
    violations.push({ mention, source });
  };

  // (1) Real staff names. Exact, and independent of any title.
  const haystack = normalizeEntityText(text);
  for (const doctor of input.clinicDoctors) {
    const key = normalizeEntityText(doctor.name);
    if (!key || key.length < 4) continue;
    if (!haystack.includes(key)) continue;
    if (isAllowed(doctor.name)) continue;
    flag(doctor.name, "clinic_directory");
  }

  // (2) Anything written as a doctor's name that matches nothing offered.
  for (const mention of titledMentions(text)) {
    if (isAllowed(mention)) continue;
    flag(mention, "titled_mention");
  }

  // (3) The closed world, for turns whose subject is who the doctors are.
  if (input.rosterBearing) {
    const candidates = personNameCandidates(text);
    if (allowed.length === 0) {
      // Nothing authoritative came back this turn, so there is no true way to
      // name anybody: every candidate is unbacked by construction, whether or
      // not it happens to be a real person somewhere.
      //
      // The trigger is a *named* person and not a bare title, because "تحب
      // تحجز مع دكتور؟" and "you can book with any doctor" mention doctors
      // without claiming membership, and replacing those would be a regression
      // for no gain. The moment a name appears, the claim is a membership claim.
      for (const candidate of candidates) {
        if (isOtherEntity(candidate)) continue;
        flag(candidate, "unbacked_roster");
      }
    } else {
      for (const candidate of candidates) {
        if (isAllowed(candidate) || isOtherEntity(candidate)) continue;
        flag(candidate, "unlisted_name");
      }
    }
  }

  return { grounded: violations.length === 0, violations };
}

/**
 * Words that defer a name rather than being one.
 *
 * "الدكتور المتاح كمان **هو** نادية شوقي" and "The doctor available in Gamma
 * Unit **is** Rana Wasfy" are the shape P11 §11 recorded as uncatchable: the
 * titled span opens with prose, so reading only the tokens immediately after
 * the title yields nothing and the name that follows was never examined. A
 * copula is the hinge — what comes after it in a titled span is the name the
 * sentence is asserting — so the reader now takes a second look from there.
 */
const COPULAS = new Set(["is", "are", "هو", "هي", "هما", "هم"]);

/**
 * The run of name-like tokens starting at `text`, or null if it is all prose.
 *
 * Truncating at the first ordinary word is what separates "نادية شوقي" out of
 * "الدكتورة نادية شوقي متاحة بكرة" from nothing at all out of "الدكتور المعالج
 * بتاعك…", where the very first word is already prose.
 */
function leadingNameRun(
  text: string,
  options: { afterCopula?: boolean } = {},
): string | null {
  const span = text.split(/[\n\r,،.؟?!:;()\[\]"«»]|\s[-–—]\s/u)[0] ?? "";
  const words = span
    .trim()
    .split(/\s+/)
    .filter(Boolean)
    .filter((token) => /[\p{L}]/u.test(token));

  const readFrom = (start: number): string | null => {
    const run: string[] = [];
    for (const token of words.slice(start, start + MAX_NAME_TOKENS)) {
      if (FUNCTION_WORDS.has(token.toLocaleLowerCase("en"))) break;
      run.push(token);
    }
    return run.length === 0 ? null : run.join(" ");
  };

  const direct = readFrom(0);
  if (direct || !options.afterCopula) return direct;

  // The span opened with prose. If it turns on a copula, the assertion is
  // whatever follows it.
  const hinge = words.findIndex((token) =>
    COPULAS.has(token.toLocaleLowerCase("en")),
  );
  return hinge === -1 ? null : readFrom(hinge + 1);
}

/** The name-shaped spans written after a doctor title. */
export function titledMentions(text: string): string[] {
  const out: string[] = [];
  const source = stripPresentationMarkup(text);
  DOCTOR_TITLE.lastIndex = 0;
  for (const match of source.matchAll(DOCTOR_TITLE)) {
    const rest = source.slice((match.index ?? 0) + match[0].length);
    const run = leadingNameRun(rest, { afterCopula: true });
    if (run) out.push(run);
  }
  return out;
}

/**
 * Every span in the reply that is shaped like a person's name.
 *
 * Used only under the closed-world rule, where the cost of a false positive is
 * a correct deterministic answer rather than a wrong one. Three shapes, which
 * between them cover how a roster is actually written:
 *
 *   * after a title — `Dr. <First> <Last>`, `د. <الاسم>`;
 *   * as an enumerated item — `1. <First> <Last>`, `- <الاسم>`, where the model
 *     dropped the title;
 *   * as a capitalized multi-word run mid-sentence — the shape P11 §11 named
 *     as uncaught.
 */
export function personNameCandidates(text: string): string[] {
  const out = new Set<string>();
  for (const mention of titledMentions(text)) out.add(mention);

  // Enumerated list items, read from the *unstripped* text so the marker that
  // introduces the item is still there to be recognised.
  for (const match of text.matchAll(
    /^[ \t]*(?:\d{1,2}[.)]|[-–—•·])[ \t]+(.*)$/gmu,
  )) {
    const item = stripPresentationMarkup(match[1] ?? "").trim();
    // An item may lead with its own title; drop it and read what follows.
    const withoutTitle = item.replace(
      /^(?:(?:drs?|doctors?|prof)|(?:ال)?(?:دكاترة|دكتوره|دكتورة|دكتور|د))(?:[.:\-–]+\s*|\s+)/iu,
      "",
    );
    const run = leadingNameRun(withoutTitle);
    if (run) out.add(run);
  }

  // Capitalized multi-word Latin runs. Two tokens minimum, because a single
  // capitalized word is far more often a department, a day or a sentence start
  // than a person.
  //
  // The separator is `[ \t]` and not `\s`, deliberately: with `\s` a run
  // crossed the newline between two list items and the two names became one
  // span that existed in neither, which then failed to match either real name
  // in the *backed* case.
  const stripped = stripPresentationMarkup(text);
  for (const match of stripped.matchAll(
    /(?<![\p{L}\p{N}])(\p{Lu}[\p{L}'’-]+(?:[ \t]+\p{Lu}[\p{L}'’-]+){1,3})/gu,
  )) {
    const span = match[1] ?? "";
    const tokens = span.split(/\s+/).filter(Boolean);
    if (tokens.some((token) => FUNCTION_WORDS.has(token.toLocaleLowerCase("en")))) {
      continue;
    }
    // A capitalized run introduced by a locative is a place, not a person:
    // "available in Gamma Unit" names a department, and treating it as an
    // unlisted doctor would reject a sentence whose doctor was entirely correct.
    const before = stripped.slice(0, match.index ?? 0);
    if (/(?:\bin|\bat|\bof|\bfrom|\bto|قسم|في)[ \t]*$/iu.test(before)) continue;
    out.add(tokens.join(" "));
  }

  return [...out];
}

// ---------------------------------------------------------------------------
// Repair
// ---------------------------------------------------------------------------

/**
 * The instruction added to the second attempt.
 *
 * It states the permitted set rather than scolding, because a model that has
 * just invented a name needs the true list in front of it more than it needs a
 * rule it has already read.
 */
export function buildGroundingCorrection(input: {
  locale: "ar" | "en";
  allowedNames: readonly string[];
  violations: readonly GroundingViolation[];
}): string {
  const names = input.allowedNames.join(input.locale === "ar" ? "، " : ", ");
  const offending = input.violations.map((item) => item.mention).join(", ");
  if (input.locale === "ar") {
    return (
      "تصحيح إلزامي: ردّك السابق ذكر اسمًا لم يُرجعه النظام في هذا الدور" +
      (offending ? ` (${offending})` : "") +
      ". " +
      (names
        ? `الأطباء الوحيدون المسموح بذكرهم الآن هم: ${names}. اذكرهم جميعًا ولا تضف أي اسم آخر.`
        : "لا توجد قائمة أطباء من النظام في هذا الدور، فلا تذكر أي اسم طبيب إطلاقًا — " +
          "استدعِ الأداة المناسبة أولًا.") +
      " أعد كتابة الرد بنفس الأسلوب واللغة."
    );
  }
  return (
    "Mandatory correction: your previous reply named someone the server did not return " +
    "on this turn" +
    (offending ? ` (${offending})` : "") +
    ". " +
    (names
      ? `The only doctors you may name right now are: ${names}. Name all of them and add no one else.`
      : "No server-returned doctor list exists on this turn, so name no doctor at all — call " +
        "the appropriate tool first.") +
    " Rewrite the reply in the same style and language."
  );
}

/**
 * The deterministic answer, used only when the model has failed the contract
 * twice. Composed from the authoritative roster, so it is true by construction.
 */
export function buildDeterministicRosterReply(input: {
  locale: "ar" | "en";
  departmentName: string | null;
  doctors: readonly string[];
  departments: readonly string[];
}): string {
  const ar = input.locale === "ar";
  const vertical = (values: readonly string[]) =>
    values.map((value, index) => `${index + 1}. ${value}`).join("\n");
  // P11F — stored labels are data. They do not choose the language of a reply,
  // and a department the clinic spelled "Physical Therapy" is "العلاج الطبيعي"
  // in an Arabic sentence. See `entity-labels.ts`.
  const department = localizeEntityLabel(input.departmentName, input.locale);
  const formattedDoctors = formatPersonNames(input.doctors, input.locale);
  const formattedDepartments = localizeEntityLabels(input.departments, input.locale);
  if (!department) {
    if (input.departments.length === 0) {
      return ar
        ? "معلش، مش لاقي أقسام متاحة للحجز دلوقتي. تحب أوصلك بموظفي العيادة؟"
        : "Sorry — I cannot find any bookable departments right now. Would you like me to pass you to clinic staff?";
    }
    return ar
      ? `الأقسام المتاحة عندنا:\n${vertical(formattedDepartments)}\nتحب تحجز في أنهي قسم؟`
      : `The departments we have are:\n${vertical(formattedDepartments)}\nWhich one would you like?`;
  }
  if (input.doctors.length === 0) {
    return ar
      ? `مفيش دكتور متاح للحجز في ${department} حاليًا. تحب تختار قسم تاني أو أوصلك بموظفي العيادة؟`
      : `There is no bookable doctor in ${department} at the moment. Would you like another department, or shall I pass you to clinic staff?`;
  }
  if (input.doctors.length === 1) {
    return ar
      ? `الدكتور المتاح حاليًا في ${department} هو ${formattedDoctors[0]}. تحب أحجزلك معاه؟`
      : `The doctor currently available in ${department} is ${formattedDoctors[0]}. Would you like to book with them?`;
  }
  return ar
    ? `الدكاترة المتاحين في ${department}:\n${vertical(formattedDoctors)}\nتحب تحجز مع مين؟`
    : `Available in ${department}:\n${vertical(formattedDoctors)}\nWho would you like to book with?`;
}

/**
 * P11D — the two sentences a *continued* booking needs.
 *
 * `buildDeterministicRosterReply` answers "who is in this department?". These
 * answer the two turns that follow it, and they exist for the same reason: when
 * the server has resolved something authoritatively, the patient should be told
 * what the server resolved, not a second guess from a model that has already
 * been wrong once this turn.
 *
 * Both take names the caller has already restricted to the offered roster, so
 * neither can widen what the patient sees.
 */
export function buildDeterministicDoctorChoiceReply(input: {
  locale: "ar" | "en";
  doctors: readonly string[];
}): string {
  const ar = input.locale === "ar";
  const list = formatPersonNames(input.doctors, input.locale)
    .map((doctor, index) => `${index + 1}. ${doctor}`)
    .join("\n");
  return ar
    ? `تقصد مين بالظبط؟\n${list}`
    : `Which one do you mean?\n${list}`;
}

/**
 * The chosen doctor's real bookable days.
 *
 * `days` is whatever the availability engine returned, already formatted by the
 * caller in the clinic's timezone. An empty list is a true and useful answer —
 * "nobody has a slot" — and is deliberately not phrased as a failure.
 */
export function buildDeterministicDaysReply(input: {
  locale: "ar" | "en";
  doctorName: string;
  days: readonly string[];
}): string {
  const ar = input.locale === "ar";
  const doctor = formatPersonName(input.doctorName, input.locale);
  if (input.days.length === 0) {
    return ar
      ? `تمام، ${doctor}. بس مفيش مواعيد متاحة معاه في الفترة الجاية. تحب تختار دكتور تاني أو أوصلك بموظفي العيادة؟`
      : `Alright — ${doctor}. There are no open days in the coming period. Would you like a different doctor, or shall I pass you to clinic staff?`;
  }
  const list = input.days
    .map((day) => `- ${formatPatientDate(day, input.locale)}`)
    .join("\n");
  return ar
    ? `تمام، ${doctor}. الأيام المتاحة معاه:\n${list}\nتحب أنهي يوم؟`
    : `Alright — ${doctor}. Available days:\n${list}\nWhich day suits you?`;
}

// ---------------------------------------------------------------------------
// P11F — the rest of the ladder
// ---------------------------------------------------------------------------

/**
 * The sentences a booking needs *after* the doctor is chosen.
 *
 * P11D gave the deterministic path a roster reply and a days reply, and the
 * production trace then walked straight off the end of them: the patient picked
 * a day, then a time, and the fallback — having nothing to say about either —
 * re-rendered the roster it *did* have a sentence for. A ladder with two rungs
 * missing is not a ladder, so these are the missing rungs.
 *
 * Every one of them takes values the caller has already restricted to what the
 * server actually offered, so none can widen what the patient sees, and every
 * label goes through `entity-labels.ts` for the same reason the roster reply
 * does.
 */
export function buildDeterministicTimesReply(input: {
  locale: "ar" | "en";
  doctorName: string;
  date: string;
  times: readonly string[];
}): string {
  const ar = input.locale === "ar";
  const doctor = formatPersonName(input.doctorName, input.locale);
  if (input.times.length === 0) {
    return ar
      ? `للأسف مفيش مواعيد فاضية مع ${doctor} يوم ${input.date}. تحب نشوف يوم تاني؟`
      : `There are no open times with ${doctor} on ${input.date}. Shall we look at another day?`;
  }
  const list = input.times
    .map((time) => `- ${formatPatientTime(time, input.locale)}`)
    .join("\n");
  return ar
    ? `تمام، يوم ${input.date}. المواعيد المتاحة مع ${doctor}:\n${list}\nتحب أنهي معاد؟`
    : `Alright — ${input.date}. Times available with ${doctor}:\n${list}\nWhich one suits you?`;
}

/**
 * "Which time did you mean?" — asked only among times that were offered.
 *
 * A bare "9" when both 09:00 and 21:00 are open is a real ambiguity and the
 * only honest answer is the question. It is emphatically *not* a reason to go
 * back to the doctor roster, which is what used to happen.
 */
export function buildDeterministicTimeChoiceReply(input: {
  locale: "ar" | "en";
  date: string;
  times: readonly string[];
}): string {
  const ar = input.locale === "ar";
  const list = input.times
    .map((time) => `- ${formatPatientTime(time, input.locale)}`)
    .join("\n");
  return ar
    ? `تحب أنهي معاد بالظبط يوم ${input.date}؟\nالمتاح:\n${list}`
    : `Which time on ${input.date} exactly?\nAvailable:\n${list}`;
}

/** The Arabic and English names of the intake fields, for the ask. */
const INTAKE_FIELD_NAMES: Readonly<Record<string, { ar: string; en: string }>> = {
  full_name: { ar: "الاسم الكامل", en: "full name" },
  national_id: { ar: "رقم الهوية", en: "national ID" },
  date_of_birth: { ar: "تاريخ الميلاد", en: "date of birth" },
  email: { ar: "البريد الإلكتروني", en: "email address" },
  phone: { ar: "رقم الموبايل", en: "mobile number" },
  gender: { ar: "النوع", en: "gender" },
  blood_type: { ar: "فصيلة الدم", en: "blood type" },
};

/**
 * "Before I send the request I still need…" — the intake ask that **states the
 * booking target back**.
 *
 * The restatement is the point. A patient who has just chosen a doctor, a day
 * and a time and is then asked for a date of birth has every reason to wonder
 * whether the booking survived; and an assistant that says "for Dr X on the
 * 31st at 09:00, I still need…" cannot then quietly lose it, because the
 * sentence and the state are built from the same three values.
 */
export function buildDeterministicIntakeReply(input: {
  locale: "ar" | "en";
  doctorName: string;
  date: string | null;
  time: string | null;
  missingFields: readonly string[];
  /** True when the appointment is for somebody other than the sender. */
  forOther: boolean;
}): string {
  const ar = input.locale === "ar";
  const doctor = formatPersonName(input.doctorName, input.locale);
  const target = ar
    ? [
        doctor ? `مع ${doctor}` : "",
        input.date ? `يوم ${input.date}` : "",
        input.time ? `الساعة ${input.time}` : "",
      ]
        .filter(Boolean)
        .join(" ")
    : [
        doctor ? `with ${doctor}` : "",
        input.date ? `on ${input.date}` : "",
        input.time ? `at ${input.time}` : "",
      ]
        .filter(Boolean)
        .join(" ");
  const fields = input.missingFields
    .map((field) => INTAKE_FIELD_NAMES[field]?.[ar ? "ar" : "en"] ?? field)
    .join(ar ? "، " : ", ");
  const whose = ar
    ? input.forOther
      ? "بيانات المريض"
      : "بياناتك"
    : input.forOther
      ? "the patient's details"
      : "your details";
  if (fields.length === 0) {
    return ar
      ? `تمام، الحجز ${target}. خليني أكمّل الطلب دلوقتي.`
      : `Alright — the appointment ${target}. Let me put the request through now.`;
  }
  return ar
    ? `تمام، حجزنا ${target}. قبل ما أبعت الطلب محتاج ${whose}: ${fields}.`
    : `Alright — the appointment is ${target}. Before I send the request I need ${whose}: ${fields}.`;
}

/** The appointment request is in. Restates exactly what was requested. */
export function buildDeterministicPendingBookingReply(input: {
  locale: "ar" | "en";
  doctorName: string;
  date: string;
  time: string;
}): string {
  const ar = input.locale === "ar";
  const doctor = formatPersonName(input.doctorName, input.locale);
  return ar
    ? `تمام، بعتّ طلب الحجز مع ${doctor} يوم ${input.date} الساعة ${input.time}. العيادة هتأكّده وهنبعتلك رسالة.`
    : `Done — I have sent the appointment request with ${doctor} on ${input.date} at ${input.time}. The clinic will confirm it and we will message you.`;
}

/** A step that failed revalidation, said plainly. Never a restart. */
export function buildDeterministicRevalidationReply(input: {
  locale: "ar" | "en";
  reason: "slot_taken" | "day_taken" | "doctor_unavailable" | "too_soon";
  doctorName: string | null;
}): string {
  const ar = input.locale === "ar";
  const doctor = formatPersonName(input.doctorName ?? "", input.locale);
  switch (input.reason) {
    case "slot_taken":
      return ar
        ? "للأسف المعاد ده اتحجز توّه. تحب تختار معاد تاني من المتاح؟"
        : "That time has just been taken. Would you like to pick another one from the open times?";
    case "day_taken":
      return ar
        ? "للأسف اليوم ده مابقاش فيه مواعيد. تحب نشوف يوم تاني؟"
        : "That day no longer has open times. Shall we look at another day?";
    case "too_soon":
      return ar
        ? "الحجز محتاج ٢٤ ساعة على الأقل قبل الميعاد. تحب نختار معاد أبعد شوية؟"
        : "Bookings need at least 24 hours' notice. Shall we pick a slightly later slot?";
    case "doctor_unavailable":
    default:
      return ar
        ? `للأسف ${doctor || "الدكتور"} مابقاش متاحًا للحجز حاليًا. دي الأسماء المتاحة دلوقتي:`
        : `${doctor || "That doctor"} is no longer available for booking. Here is who is available now:`;
  }
}
